### PR TITLE
Ap tabbed interface

### PR DESCRIPTION
**Pull request by andrewp8**

### CODE REVIEW

**Review by ajmompr — CHANGES_REQUESTED** [review]
Hi Andrew! Nice job creating your tabbed interface; however, I am currently unable to review your following and followers tabs. I am receiving a routing error, so please be sure to define those routes. Also, every time I select one of the links in your tabbed interface, I receive an empty alert.

**Comment by andrewp8** [comment]
I just fixed the routes and alert issue. Can you re-check? Thank you

**Review by ajmompr — APPROVED** [review]
Hi Andrew! Thank you so much for making the requested changes/updating your routes and correcting your alerts. I like the fun styling and your tabbed interface is now fully functional. Please submit your link to canvas, and I will update your grade!

**Comment by andrewp8** [comment]
Thank you Alex!

**Pull request merged**
