### PR TITLE
Ap starting on UI

### PR DESCRIPTION
**Pull request by andrewp8**

### CODE REVIEW

**Review by prettyalana — APPROVED** [review]
Looks good!

**Review by ajmompr — CHANGES_REQUESTED** [review]
Hi Andrew! May you please edit your pull request so that we are comparing your starting-on-ui to your photogram-industrial-2 branch? Currently, your pull request is set up to compare to your main branch. For this assignment, we are creating feature branches from the previous feature branch! Let me know if you have any questions.

**Comment by andrewp8** [comment]
> Hi Andrew! May you please edit your pull request so that we are comparing your starting-on-ui to your photogram-industrial-2 branch? Currently, your pull request is set up to compare to your main branch. For this assignment, we are creating feature branches from the previous feature branch! Let me know if you have any questions.

HI Alex, I changed the compare branch to photogram-industrial-2 as you suggested. Thank you.

**Comment by ajmompr** [comment]
Hi Andrew! Thank you for making the requested changes. Your feature branch is functional, and I was able to rake sample_data and review the current iteration of your app. I will update your grade in Canvas!

**Review by ajmompr — APPROVED** [review]
Thank you for making requested changes

**Comment by andrewp8** [comment]
Thank you Alex.

**Pull request merged**
